### PR TITLE
fix(aws-cloudwatch-metrics): added priorityClassName

### PR DESCRIPTION
**Pull request by ib-ak**
### Issue
#700 

### Description of changes

adds priorityClassName to aws-cloudwatch-metrics daemonset if value is present

### Checklist
- [x] Added/modified documentation as required (such as the `README.md` for modified charts)
- [x] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [x] Manually tested. Describe what testing was done in the testing section below
- [x] Make sure the title of the PR is a good description that can go into the release notes

### Testing

TC1: Run helm template . without making any change to values.yaml. 
Expected Result: priorityClassName should not be added to ds.
Actual Result: priorityClassName  was not added.

TC2: Run helm template . after adding  "priorityClassName: pc" to values.yaml. 
Expected Result: priorityClassName: pc should be added to ds.
Actual Result: priorityClassName : pc was added.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by abhinavkhanna-sf** [comment]
@bwagner5 @kishorj @jaypipes Let me know if you need anything else for this.

**Comment by abhinavkhanna-sf** [comment]
@codeJack Are you codeowner for this repo now? Can you review this ?

**Comment by dallasanta** [comment]
This has been pending review for a while. @PettitWesley  you think you could help here? Thanks!

**Comment by PettitWesley** [comment]
@dallasanta I only help with the fluent bit chart here, sorry

**Comment by dallasanta** [comment]
Hi @jaypipes, we're struggling to find reviewers here and you have merged the last two PR on aws-cloudwatch-metrics. Would you please advise if you're able to have a look or, alternatively, tag someone that could? Thank you.

**Review by bwagner5 — APPROVED** [review]
LGTM

**Pull request merged**
