### PR TITLE
Release CNI Metrics Helper helm chart

### PR DESCRIPTION
**Pull request by jdn5126**
### Issue
#155 

### Description of changes
This PR adds the CNI Metrics Helper chart to eks-charts repo. The chart is synced from here: https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/cni-metrics-helper

This is done so that customers can install CNI Metrics Helper from eks-charts repo.

### Checklist
- [x] Added/modified documentation as required (such as the `README.md` for modified charts)
- [x] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [x] Manually tested. Describe what testing was done in the testing section below
- [x] Make sure the title of the PR is a good description that can go into the release notes

### Testing
Verified that chart can be installed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jdn5126** [comment]
Holding off on merging this until I can clean up chart a bit

**Comment by jdn5126** [comment]
This PR is waiting to merge until https://github.com/aws/amazon-vpc-cni-k8s/pull/2201 merges

**Comment by jdn5126** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/pull/2201 has merged, so this is just waiting on review

**Review by jayanthvn — APPROVED** [review]
lgtm

**Pull request merged**
