### PR TITLE
[aws-for-fluent-bit] Add Replace_Dots option to fluent-bit elasticsearch output #297

### PR DESCRIPTION
**Pull request by dpujadas**
Issue #297

Description of changes:

Add Replace_Dots option to fluent-bit elasticsearch output

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by PettitWesley — APPROVED** [review]

**Comment by fawadkhaliq** [comment]
@dpujadas thanks for the PR. can you please increment the chart version to 0.1.7 as 0.1.6 is the current published chart and has been released. If you rebase, circle CI will catch this

**Review by PettitWesley — APPROVED** [review]

**Comment by jasonumiker** [comment]
I just wanted to +1 this - without this option all my fluent-bits get hung up on something with a dot that is in the cluster by default and stop shipping any logs. So I go and manually edit the configmap after deploying the chart to add this option and it all starts working again. I consider our chart broken unless this option is possible via its values - and agree it should be the default.

**Comment by jasonumiker** [comment]
https://github.com/aws/eks-charts/pull/491 - the issue with the failing checks is likely that you merged another PR ahead of this one that 'stole' the version number. I have created a new PR that is this one but incremented the version number again that should be mergable...

**Comment by jaypipes** [comment]
@dpujadas I added you as Co-authored-by on #362 from @jasonumiker which I was able to resolve conflicts on. This PR can now be closed. Apologies again for the delays and thanks for your patience.

**Pull request closed without merging**
