### PR TITLE
Sync vpc-cni charts from master branch

### PR DESCRIPTION
**Pull request by cgchinmay**
### Description of changes
vpc-cni Chart failed to sync with this repo . So had to create this manually 

### Checklist
- [x] Added/modified documentation as required (such as the `README.md` for modified charts)
- [x] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [x] Manually tested. Describe what testing was done in the testing section below
- [x] Make sure the title of the PR is a good description that can go into the release notes

### Testing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jayanthvn — APPROVED** [review]

**Comment by jayanthvn** [comment]
This would need an EKS-charts release.

**Comment by sidewinder12s** [comment]
@jayanthvn @cgchinmay I think in the manual sync you missed the new probe timeout values in the daemonset template: 

```
livenessProbeTimeoutSeconds
readinessProbeTimeoutSeconds
```

**Comment by jayanthvn** [comment]
Thanks @sidewinder12s, @cgchinmay is working on 1.10.2 release and we will fix it.

**Comment by sidewinder12s** [comment]
Could probably just stuff the timeout config into the existing templated probe configs.

**Comment by cgchinmay** [comment]
> Could probably just stuff the timeout config into the existing templated probe configs.
We have scheduled release before end of this week, so will add these changes as well.

**Pull request merged**
