### PR TITLE
[aws-vpc-cni] bump version & modify cri hostPath

### PR DESCRIPTION
**Pull request by cw-sakamoto**
### Description of changes

- bump image tag
- modify hostPath for `cri`

### Checklist
- [x] Added/modified documentation as required (such as the `README.md` for modified charts)
- [x] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [x] Manually tested. Describe what testing was done in the testing section below
- [x] Make sure the title of the PR is a good description that can go into the release notes

### Testing

before change

```
      - name: cri
        hostPath:
          path:
                  path: /var/run/containerd/containerd.sock
```

after change
```
      - name: cri
        hostPath:
          path: /var/run/containerd/containerd.sock
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jayanthvn** [comment]
Thanks for fixing it, we might also want to fix it here - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/daemonset.yaml

**Comment by cw-sakamoto** [comment]
@jayanthvn Thanks for your comment.
Yes, I will fix it later, including the README.


There are two charts for `aws-vpc-cni`, and the contents seem to be the same, but which one should I use?

**Comment by jayanthvn** [comment]
> @jayanthvn Thanks for your comment.
> I will fix it later, including the README.
> 
> There are two charts for `aws-vpc-cni`, and the contents seem to be the same, but which one should I use?

Thank you so much. We will make updates to the chart folder here - https://github.com/aws/amazon-vpc-cni-k8s and then do a sync to https://github.com/aws/eks-charts.

**Review by jayanthvn — APPROVED** [review]
LGTM :)

**Pull request merged**
