### PR TITLE
Add podLabels for appmesh-controller

### PR DESCRIPTION
**Pull request by limed**
Issue #203:

Description of changes:
- Add `podLabels` to the `appmesh-controller` chart
- Helps resolve issue #203 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by fawadkhaliq** [comment]
@limed thanks for the PR. Some other changes got merged before this so you will need to rebase/resolve conflicts before we can get this in

**Comment by limed** [comment]
> @limed thanks for the PR. Some other changes got merged before this so you will need to rebase/resolve conflicts before we can get this in

@fawadkhaliq I've rebased the branch but it looks like the tests are failing due to the CI image `fawadkhaliq/appmesh-controller:v1.0.0-rc5` running an older version of the controller. 

The tests are failing due a missing flag
```
unknown flag: --sidecar-cpu-limits
```

Which got added ~8 days ago in commit fa911c740ffcf835a44a4ef71346b152308ffc41 so you should update the CI image before this test can pass

**Comment by fawadkhaliq** [comment]
> > @limed thanks for the PR. Some other changes got merged before this so you will need to rebase/resolve conflicts before we can get this in
> 
> @fawadkhaliq I've rebased the branch but it looks like the tests are failing due to the CI image `fawadkhaliq/appmesh-controller:v1.0.0-rc5` running an older version of the controller.
> 
> The tests are failing due a missing flag
> 
> ```
> unknown flag: --sidecar-cpu-limits
> ```
> 
> Which got added ~8 days ago in commit [aws/aws-app-mesh-controller-for-k8s@fa911c7](https://github.com/aws/aws-app-mesh-controller-for-k8s/commit/fa911c740ffcf835a44a4ef71346b152308ffc41) so you should update the CI image before this test can pass

Thanks. I'll address this in the next PR. The image is being updated

**Comment by fawadkhaliq** [comment]
@limed https://github.com/aws/eks-charts/pull/225 fixes the image. Can you please also bump the charts version [1] in your PR so the CI passes 

[1] https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/Chart.yaml#L4

**Comment by limed** [comment]
> @limed #225 fixes the image. Can you please also bump the charts version [1] in your PR so the CI passes
> 
> [1] https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/Chart.yaml#L4

Done in https://github.com/aws/eks-charts/pull/221/commits/23826500bb1082d68c818903d7e7ac09d880efb4

**Pull request merged**
