### PR TITLE
aws-for-fluent-bit: support cri multiline parsing

### PR DESCRIPTION
**Pull request by PettitWesley**
### Checklist
- [ ] Added/modified documentation as required (such as the `README.md` for modified charts)
- [ ] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [ ] Manually tested. Describe what testing was done in the testing section below
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### Testing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by PettitWesley** [comment]
New input conf with default values:

```
$ helm template --dry-run --debug aws-for-fluent-bit stable/aws-for-fluent-bit/ --values stable/aws-for-fluent-bit/values.yaml

data:
  fluent-bit.conf: |
    [SERVICE]
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_PORT    2020
        Health_Check On
        HC_Errors_Count 5
        HC_Retry_Failure_Count 5
        HC_Period 5

        Parsers_File /fluent-bit/parsers/parsers.conf
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        multiline.parser  docker, cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```

**Comment by PettitWesley** [comment]
Generated tail input with the old default values.yaml:

```
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Parser            docker
        Docker_Mode       On
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```

```
input:
  enabled: true
  tag: "kube.*"
  path: "/var/log/containers/*.log"
  db: "/var/log/flb_kube.db"
  # multilineParser: "docker, cri"
  parser: docker
  dockerMode: "On"
  memBufLimit: 5MB
  skipLongLines: "On"
  refreshInterval: 10
```

**Comment by PettitWesley** [comment]
Successfully deployed the new daemonset on a bottlerocket 1.25 EKS cluster, checked that the cri logs are properly formatted:

```
{
    "time": "2023-10-18T20:41:51.610143829Z",
    "stream": "stderr",
    "_p": "F",
    "log": "I1018 20:41:51.610028       1 proxier.go:850] \"Syncing iptables rules\"",
    "kubernetes": {
        "pod_name": "kube-proxy-jsgfc",
        "namespace_name": "kube-system",
        "pod_id": "37ea6ab2-e32b-4d34-9c97-e059c89844d0",
        "labels": {
            "controller-revision-hash": "874768548",
            "k8s-app": "kube-proxy",
            "pod-template-generation": "1"
        },
        "host": "ip-192-168-43-86.ca-central-1.compute.internal",
        "container_name": "kube-proxy",
        "docker_id": "40c90418e671cc466cb20d9f380ae578c0db2819fb097fb2db5320b1ef253ef9",
        "container_hash": "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/kube-proxy@sha256:7d1ed1e2f1f2ba5ca729a9d5417ff7db799390b6b2360edb8074d6758ca69987",
        "container_image": "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/kube-proxy:v1.25.6-minimal-eksbuild.1"
    }
}
```

**Review by hossain-rayhan — APPROVED** [review]

**Comment by PettitWesley** [comment]
I also deployed the new template with the old values.yaml just to make sure that deploys cleanly and thus the update should not break anyone.

**Pull request merged**
