### PR TITLE
fix(fluentbit): rewrite erroneous ident

### PR DESCRIPTION
**Pull request by JBOClara**
### Issue

typo in templating 

```
        {{- if .Values.opensearch.extraOutputs }}
{{ .Values.opensearch.extraOutputsIndent_8 }}
        {{- end }}
```

### Description of changes

fix the typo 

### Checklist
- [X] Added/modified documentation as required (such as the `README.md` for modified charts)
- [X] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [X] Manually tested. Describe what testing was done in the testing section below
- [X] Make sure the title of the PR is a good description that can go into the release notes

### Testing

Deploy the fixed version

With this as a value:

```yaml
opensearch:
...
  extraOutputs: |
    Retry_Limit    6
```

Before the fix
```
    [OUTPUT]
        Name                opensearch
        Match               kube.*
        AWS_Region                ${AWS_REGION}
        AWS_Auth                On
        Host                XXXX
        Port                443
        tls                on
        Buffer_Size         False
        AWS_Role_ARN        XXXX
        Type                _doc
        Logstash_Format     on
        Logstash_Prefix     eks-preprod
        Logstash_DateFormat %Y.%m.%d
        Time_Key            @timestamp
        Time_Key_Format     %Y-%m-%dT%H:%M:%S
        Time_Key_Nanos      On
        Include_Tag_Key     On
        Tag_Key             tag
        Generate_ID         On
        Write_Operation     create
        Replace_Dots        On
        Trace_Output        Off
        Trace_Error         On
        Current_Time_Index  Off
        Suppress_Type_Name  Off
```

After the fix
```
    [OUTPUT]
        Name                opensearch
        Match               kube.*
        AWS_Region                ${AWS_REGION}
        AWS_Auth                On
        Host                XXXX
        Port                443
        tls                on
        Buffer_Size         False
        AWS_Role_ARN        XXXX
        Type                _doc
        Logstash_Format     on
        Logstash_Prefix     eks-preprod
        Logstash_DateFormat %Y.%m.%d
        Time_Key            @timestamp
        Time_Key_Format     %Y-%m-%dT%H:%M:%S
        Time_Key_Nanos      On
        Include_Tag_Key     On
        Tag_Key             tag
        Generate_ID         On
        Write_Operation     create
        Replace_Dots        On
        Trace_Output        Off
        Trace_Error         On
        Current_Time_Index  Off
        Suppress_Type_Name  Off
        Retry_Limit    6
```

### CODE REVIEW

**Comment by JBOClara** [comment]
@PettitWesley @hossain-rayhan 
Could you review this PR ?

**Review by PettitWesley — APPROVED** [review]
@JBOClara Can you run the template dry run quickly and submit the output to this PR as evidence of testing? And then I will merge it to ensure we get this fixed.

Right now, does this just prevents opensearch.extraOutputs from being used right? Or does it block all users of the chart?

**Comment by PettitWesley** [comment]
Ping me after you run the dry run and I will merge and release it.

Thanks!

**Comment by JBOClara** [comment]
> @JBOClara Can you run the template dry run quickly and submit the output to this PR as evidence of testing? And then I will merge it to ensure we get this fixed.


@PettitWesley 
I've fixed a little formatting issue (EOL) and added the


> Right now, does this just prevents opensearch.extraOutputs from being used right? Or does it block all users of the chart?

Yes, this just prevents opensearch.extraOutputs from being used right.

**Review by PettitWesley — APPROVED** [review]

**Comment by PettitWesley** [comment]
Thanks!

**Comment by PettitWesley** [comment]
@JBOClara I will work on releasing this one ASAP... once I figure out how the new rlease process works in this repo

**Comment by PettitWesley** [comment]
Double checked on master myself:

```
$ helm template --dry-run . --set opensearch.enabled=true  --set opensearch.extraOutputs="extra_test_key val"

    [OUTPUT]
        Name                opensearch
        Match               *
        AWS_Region                us-east-1
        AWS_Auth                On
        Port                443
        tls                on
        Buffer_Size         5m
        Index               aws-fluent-bit
        Type                _doc
        Logstash_Format     off
        Logstash_Prefix     logstash
        Logstash_DateFormat %Y.%m.%d
        Time_Key            @timestamp
        Time_Key_Format     %Y-%m-%dT%H:%M:%S
        Time_Key_Nanos      Off
        Include_Tag_Key     Off
        Tag_Key             _flb-key
        Generate_ID         Off
        Write_Operation     create
        Replace_Dots        Off
        Trace_Output        Off
        Trace_Error         Off
        Current_Time_Index  Off
        Suppress_Type_Name  On
        extra_test_key val
```

**Comment by PettitWesley** [comment]
Draft release notes: https://github.com/aws/eks-charts/releases/edit/untagged-6f419b0051f6cc91ccd2

**Comment by PettitWesley** [comment]
@JBOClara https://github.com/aws/eks-charts/releases/tag/v0.0.137

**Pull request merged**
