### PR TITLE
[aws-vpc-cni] Updates to 1.7.5 release

### PR DESCRIPTION
**Pull request by spingel**
Updates to latest upstream release and bumps chart version.

By submitting this pull request, I confirm that my contribution
is made under the terms of the Apache 2.0 license.

Signed-off-by: Steffen Pingel <steffen.pingel@tasktop.com>

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
According to @mogren in https://github.com/aws/amazon-vpc-cni-k8s/issues/284#issuecomment-617931051 we need to update our CNI to version 1.7.5 to fix the pod restarts issue.

@M00nF1sh @fawadkhaliq can we get this reviewed and merged?

**Comment by max-rocket-internet** [comment]
Might be nice to also merge https://github.com/aws/eks-charts/pull/204 at the same time

**Comment by fawadkhaliq** [comment]
@max-rocket-internet thanks for the nudge. Changes looks good

cc: @jayanthvn to take a look before we merge

**Review by fawadkhaliq — APPROVED** [review]

**Review by jayanthvn — APPROVED** [review]
LGTM, thanks :)

**Pull request merged**
