### PR TITLE
Add automatic creation of ENIConfig's

### PR DESCRIPTION
**Pull request by Kent1**
Added the creation of the ENIConfig to Helm. That allows to pass, for example in our case, the created subnets and SGs from terraform and pass them to Helm.
I used availability zone for the name of ENIConfig as recommanded in the doc.

### CODE REVIEW

**Review by jayanthvn — APPROVED** [review]
LGTM, Thanks for adding this.

**Comment by fawadkhaliq** [comment]
@Kent1 can you please resolve the conflicts to move this forward

**Comment by Kent1** [comment]
done

**Comment by Kent1** [comment]
Move CRD to crds/. Should we change API from v1beta1 to v1 ?  Or is still not supported in 1.15 ?

**Comment by arunvelsriram** [comment]
Waiting for this to be merged :)

**Comment by fawadkhaliq** [comment]
Thanks for your contribution. We recently added this [1] PR template to help guide on what changes need to be made as part of the pull requests (README, chart version increment etc). The change is good to merge once the PR checklist is updated

[1] https://github.com/aws/eks-charts/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by fawadkhaliq** [comment]
@Kent1 https://github.com/aws/eks-charts/pull/472 addresses the same. Closing this

**Pull request closed without merging**
