### PR TITLE
[appmesh-controller] Fix serviceAccount annotations default value

### LINKED ISSUE #724: [appmesh-controller] `serviceAccount.annotations` default value should be an empty map
**Describe the bug**

Installing the `appmesh-controller` helm chart issues the following warning:
```
warning: destination for appmesh-controller.serviceAccount.annotations is a table. Ignoring non-table value ()
```

**Steps to reproduce**

Install the `appmesh-controller` helm chart.

**Expected outcome**

No warning.

**Environment**

* Chart name: `appmesh-controller`
* Chart version: `1.4.5`
* Kubernetes version: `1.21`
* Using EKS (yes/no), if so version? `1.21`

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #724.

### CODE REVIEW

**Comment by gitfool** [comment]
@achevuru PTAL

**Comment by gitfool** [comment]
@achevuru PTAL

**Comment by achevuru** [comment]
@[bendu](https://github.com/bendu) Can you help look at the PR?

**Comment by gitfool** [comment]
@bendu ^ (@mentioning again since mention above by achevuru looks incorrect)

**Comment by bendu** [comment]
@gitfool @achevuru  I will look at this PR, but someone else will need to merge it since I do not have write access.

**Review by bendu — APPROVED** [review]
@gitfool Thank you for your contribution!

ship it sheep

**Comment by bendu** [comment]
EKS charts is not the source of truth for the app mesh controller helm chart. I have created a PR  aws/aws-app-mesh-controller-for-k8s#577 to backfill this.

**Pull request merged**
