### PR TITLE
small change for crd url

### PR DESCRIPTION
**Pull request by kenichi-shibata**
current url does not work

Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by fawadkhaliq** [comment]
hi @kenichi-shibata thanks for submitting the PR. Can you please update the description with what the failure is when you try to run the command?

If you're using zsh or a shell that does not like the path, please add quotes to the path in README instead of changing from -k to -f:
```
kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
```

**Comment by kenichi-shibata** [comment]
Nvermind im in 1.13 

`kubectl -k` was integrated in 1.14

https://sysdig.com/blog/whats-new-kubernetes-1-14/

**Comment by fawadkhaliq** [comment]
Thanks. Looks good. The CI is failing. You will need to bump the chart version [here](https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/Chart.yaml#L4). Once done, we can merge it :)

**Comment by kenichi-shibata** [comment]
done

**Review by fawadkhaliq — APPROVED** [review]

**Pull request merged**
