### PR TITLE
aws-calico: Add probe timeout for calico-node daemon-set

### PR DESCRIPTION
**Pull request by danielwegener**
### Issue

#574

### Description of changes

Add probe timeout for daemon-set.
I'd be alternatively totally fine to make the probe section configurable via values.

### Checklist
- [ / ] Added/modified documentation as required (such as the `README.md` for modified charts)
- [ x ] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [ x ] Manually tested. Describe what testing was done in the testing section below
- [ x ] Make sure the title of the PR is a good description that can go into the release notes

### Testing

Manually added the timeoutSeconds to the deployed DaemonSet resource. This solved the problem of crash looping pods.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chris-str-cst** [comment]
Awesome, this also works for my clusters! Please get this merged

**Comment by Zyava** [comment]
@jayanthvn any chance this MR gets merged and new chart version is released? Chart (calico) is barely working for eks 1.20 right now - calico pods are constantly restarted, at the beginning just after 11 seconds since pod start (11s = timeout=1s + period=10s), network policy changes are applied with a huge delay (maybe for people with big number of network policies/nodes not applied at all, if calico pod is restarted before it managed to start, connect to typha and process all policies).

**Comment by jayanthvn** [comment]
Sorry missed reviewing. Yes for now I can merge this and take up making the probe configurable in follow up PR.

**Review by jayanthvn — APPROVED** [review]

**Comment by Zyava** [comment]
@jayanthvn thank you for merging this PR. When new version will be pushed to https://aws.github.io/eks-charts repository?
Seems like this process is not automated - 2 days later I still can't install version 0.3.8:

```
Error: chart "aws-calico" version "0.3.8" not found in https://aws.github.io/eks-charts repository
```

**Comment by jayanthvn** [comment]
Hi, We need to cut a release for eks-charts. We have an upcoming VPC CNI release this week. Once that is done, I will cut a release here too.

**Pull request merged**
