### PR TITLE
v1.12.1 chart release for VPC CNI

### PR DESCRIPTION
**Pull request by jdn5126**
### Issue
N/A

### Description of changes
v1.12.1 chart release for VPC CNI

Changes to call out:
1. Custom resource definitions moved to `crds/` folder
2. `AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER` removed
3. Tags updated

### Checklist
- [x] Added/modified documentation as required (such as the `README.md` for modified charts)
- [x] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [x] Manually tested. Describe what testing was done in the testing section below
- [x] Make sure the title of the PR is a good description that can go into the release notes

### Testing
Verified that chart can be installed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jayanthvn — APPROVED** [review]
/lgtm

**Comment by sidewinder12s** [comment]
@jdn5126 Did this fail somewhere in your deploy pipeline? The chart version still isn't resolving for me.

**Comment by jdn5126** [comment]
@sidewinder12s yeah, sorry about that. There was a deployment issue here that I am working on fixing now.

**Comment by jdn5126** [comment]
@sidewinder12s I ended up having to manually publish the chart via https://github.com/aws/eks-charts/pull/877

The chart will resolve after this PR merges

**Comment by jdn5126** [comment]
```
% helm search repo aws-vpc-cni
NAME            CHART VERSION   APP VERSION     DESCRIPTION
eks/aws-vpc-cni 1.2.2           v1.12.1         A Helm chart for the AWS VPC CNI
```
Seems to be good now, sorry for the delay

**Comment by sidewinder12s** [comment]
@jdn5126 It appears that chart version might be broken. I now see a Kustomization file attempting to be applied through ArgoCD:

https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/crds/kustomization.yaml

Which is throwing a `the server could not find the requested resource` error. 

It appears this repo might be missing a `.helmignore` parameter the vpc-cni repo has: https://github.com/aws/amazon-vpc-cni-k8s/compare/v1.12.0...v1.12.1#diff-c7df1170222bf858f908729e85545d811094ec359540fded59ec0c45713c8deb

**Comment by jdn5126** [comment]
Sorry about that, should be fixed now thanks to https://github.com/aws/eks-charts/pull/880

**Comment by sidewinder12s** [comment]
Can confirm, thanks!

**Pull request merged**
