### PR TITLE
Update App Mesh Controller CRDs

### PR DESCRIPTION
**Pull request by lavignes**
The current contoller version is v0.3.0, but the CRDs are out of date

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stefanprodan** [comment]
Please remove all non-CRD objects

**Comment by lavignes** [comment]
@stefanprodan whoops. thanks

**Comment by lavignes** [comment]
AFAIK this isn't just an enhancement but is required to fix one of our broken examples: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-grpc

^ This example was migrated to use the helm chart, but it fails due to the CRDs not having grpc support.

**Comment by lavignes** [comment]
ping. Can this get merged? We have (broken) examples that depend on this functionality.

**Comment by lavignes** [comment]
Thanks @nckturner !

**Pull request merged**
