### PR TITLE
[aws-calico] Fix indentation in deployment templates

### PR DESCRIPTION
**Pull request by casparrolfe**
Description of changes:

Fixes YAML parsing errors when setting tolerations

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by casparrolfe** [comment]
Good stuff :)

Think there is an issue with the pipeline that's preventing release. Not sure if it's been picked up or if there is anything I can do to help out!
https://app.circleci.com/pipelines/github/aws/eks-charts/542/workflows/36459561-1387-4f86-bee0-c3a8b1527dd1/jobs/1334

**Comment by casparrolfe** [comment]
@jaypipes

**Comment by stefansedich** [comment]
run

**Comment by vladlosev** [comment]
@jaypipes can you please kick off another build at https://app.circleci.com/pipelines/github/aws/eks-charts/542/workflows/36459561-1387-4f86-bee0-c3a8b1527dd1/jobs/1334? The original one failed for some reason, and did not release the new version of the chart, so the latest version of the chart is still defective.

**Comment by casparrolfe** [comment]
Not sure, sorry @pierluigilenoci - I'm not a maintainer of the repo :) Issue opened here: #244

**Pull request merged**
