### PR TITLE
[aws-load-balancer-controller]Add extraArgs

### PR DESCRIPTION
**Pull request by cw-sakamoto**
Signed-off-by: cw-sakamoto <sakamoto@chatwork.com>

Issue #, if available:

Description of changes:
- I'd like to set some arguments to the command args, but I think it depends on the use case, so I've made it so that anything can be set as `extraArgs`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cw-sakamoto** [comment]
@kishorj Thank you for your this chart maintenance. 
Can you review it?

**Comment by dza89** [comment]
I think this is better:
https://github.com/aws/eks-charts/pull/300

**Comment by kishorj** [comment]
Thank you for your contribution. We definitely need more configuration options, but IMO, we should add them individually. The blanket extraArgs is a powerful construct, however it is also prone to errors. Also, there is no documentation in the chart for what values can be safely used, and would require the user to figure them out from different places.

If there are specific configuration option that are useful for your use-case, please feel free to open a PR.

**Review by jaypipes — COMMENTED** [review]
Agree with @kishorj. The pattern we have used in all the other Charts is to use specific configuration options matching specific CLI arguments.

**Comment by kishorj** [comment]
I'm closing this PR since we do not prefer using the extraArgs option as proposed. Please feel free to open new PRs for specific config options.

**Pull request closed without merging**
