### PR TITLE
Adds parameter to create IngressClass Resource

### PR DESCRIPTION
**Pull request by emanuelflp**
### Description of changes

To use the ingressClass parameter inside of Ingress resource, the IngressClass needs to be already exists in cluster. 

This changes adds a new parameter to create ingressClass Resource.

### Checklist
- [X] Added/modified documentation as required (such as the `README.md` for modified charts)
- [X] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [X] Manually tested. Describe what testing was done in the testing section below
- [X] Make sure the title of the PR is a good description that can go into the release notes

### Testing

Set the parameter createIngressClassResource as true and install the chart. After, validade if the resource was created in kubernetes using command `kubectl get ingressclass`. After this try to create an ingress using ingressClass parameter instead of the annotation.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lazouz** [comment]
Hi,
Thank you @emanuelflp for the job you rock :) 
@kishorj @M00nF1sh , is it possible to merge this PR ? It Would be awesome 😄

**Comment by kishorj** [comment]
@emanuelflp, thanks for your contribution. Do you mind opening a PR in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/ instead? We sync the lb controller helm chart from the upstream repository.

**Comment by lazouz** [comment]
thanks @kishorj for the merge in the upstream repo !

**Comment by lazouz** [comment]
@kishorj is there something I can do to prpagate the changes here ? (version 1.2.9 of the chart)

**Comment by kishorj** [comment]
> @kishorj is there something I can do to prpagate the changes here ? (version 1.2.9 of the chart)

We are planning to include this fix in the upcoming minor version release v2.3.0.

**Pull request closed without merging**
