### PR TITLE
[aws-for-fluent-bit] Add Replace_Dots option to fluent-bit kinesis output

### PR DESCRIPTION
**Pull request by ahmad-hamade**
This PR has changes applied to `aws-for-fluent-bit` chart which includes:

* Add [Replace_Dots](https://github.com/aws/amazon-kinesis-streams-for-fluent-bit/pull/79) option to fluent-bit kinesis output
* Update default image tag to `2.13.0`

### CODE REVIEW

**Review by PettitWesley — APPROVED** [review]

**Comment by ahmad-hamade** [comment]
@hossain-rayhan @fawadkhaliq Can you please have a look at this PR?

**Comment by PettitWesley** [comment]
@fawadkhaliq the chart version needs to be incremented before I can merge this right?

> Update default image tag to 2.9.0

Sorry, I know its a been a little while since this PR was opened, can you upgrade it again to the latest version: https://github.com/aws/aws-for-fluent-bit/releases

**Comment by PettitWesley** [comment]
@ahmad-hamade I checked, you need to update the chart version: https://github.com/aws/eks-charts/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Also since you need to do that, please update the fluent bit version as well. https://github.com/aws/aws-for-fluent-bit/releases

**Comment by ahmad-hamade** [comment]
Thank you @PettitWesley.
I've updated the image and chart versions. Please let me know if anything else is left.

**Comment by jaypipes** [comment]
@ahmad-hamade apologies for the long delay on this PR and for your patience. It's now been merged.

**Pull request merged**
