### PR TITLE
fix aws-cloudwatch-metrics link in README

### PR DESCRIPTION
**Pull request by mforutan**
Issue #, if available: none

Description of changes:

Noticed a broken link in the README for `aws-cloudwatch-metrics`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by xposix — APPROVED** [review]

**Review by fawadkhaliq — APPROVED** [review]
thanks for fixing it!

**Comment by fawadkhaliq** [comment]
@mforutan I missed this earlier (noticed in the CI failure) - you need to bump the chart version [1] as well (`Chart aws-cloudwatch-metrics/ has the same Chart version as the last release..`). 

https://github.com/aws/eks-charts/blob/master/stable/aws-cloudwatch-metrics/Chart.yaml#L4

**Comment by mforutan** [comment]
> @mforutan I missed this earlier (noticed in the CI failure) - you need to bump the chart version [1] as well (`Chart aws-cloudwatch-metrics/ has the same Chart version as the last release..`).
> 
> https://github.com/aws/eks-charts/blob/master/stable/aws-cloudwatch-metrics/Chart.yaml#L4

@fawadkhaliq Thank you for the reminder, I fixed that but now it is complaining about a different chart, can you please have a look when you have a minute?

**Comment by mforutan** [comment]
@fawadkhaliq now the CI issue is fixed on the master branch, this PR is ready to be merged, thank you.

**Review by fawadkhaliq — APPROVED** [review]

**Comment by fawadkhaliq** [comment]
++ thanks!

**Pull request merged**
