### PR TITLE
Update default App Mesh Proxy Route Manager image version to v4-prod

### PR DESCRIPTION
**Pull request by suniltheta**
Description of changes:
Update Default App Mesh Proxy Route Manager Image version to v3-prod to fix above issue

### Checklist
- [n] Added/modified documentation as required (such as the `README.md` for modified charts)
- [y] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [y] Manually tested. Describe what testing was done in the testing section below
- [y] Make sure the title of the PR is a good description that can go into the release notes

### Testing

Manually tested EKS walkthrough to confirm this new v4-prod image is working as expected.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by suniltheta** [comment]
Done similar to earlier PR https://github.com/aws/eks-charts/pull/219

**Comment by cgchinmay** [comment]
appmesh-controller/Chart and appmesh-controller/Values must be updated with a PR against appmesh-controlle repo. This repo will sync those changes

**Comment by cgchinmay** [comment]
I see that appmesh-inject is deprecated, so we might not need this pull request

**Comment by cgchinmay** [comment]
Don't think we need this PR as the appmesh-inject chart is deprecated and the sidecar inject funcitonality is already part of the controller

**Pull request closed without merging**
