### PR TITLE
Update envoy image version to v1.12.2.1-prod

### PR DESCRIPTION
**Pull request by abaptiste**
Signed-off-by: Alvin Baptiste <abbaptis@amazon.com>

*Issue #, if available:*
https://github.com/aws/aws-app-mesh-roadmap/issues/141

*Description of changes:*
Update Envoy to use v1.12.2 release.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abaptiste** [comment]
@jaypipes can you take a look and please merge this PR?

**Comment by jaypipes** [comment]
@abaptiste I'm a little hesitant to merge this considering the segfaults we saw with the bad previous 1.12.2 release... do we have good data that this release is solid?

**Comment by abaptiste** [comment]
@jaypipes Yes.  We have identified why the previous build was segfaulting and have confirmed that this release does not have the same issue.

**Comment by jaypipes** [comment]
ack, OK, thanks @abaptiste :)

**Pull request merged**
