### PR TITLE
[aws-load-balancer-controller] add option to run in hostNetwork

### PR DESCRIPTION
**Pull request by jeenx**
Issue #  if available:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1591

Description of changes:
Adds hostNetwork option since the control plane is not able to reach the service when using a custom CNI (like calico) with EKS (or any managed k8s service)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kishorj** [comment]
Please update the chart version as well.

**Comment by jeenx** [comment]
@kishorj Chart version has been updated

**Review by kishorj — APPROVED** [review]

**Comment by alvarodelvalle** [comment]
@kishorj any idea when this will get merged? Thank you :)

**Comment by kishorj** [comment]
> @kishorj any idea when this will get merged? Thank you :)

Just merged

**Comment by jamestupper** [comment]
@kishorj i'm not sure if this is the actual build that publishes the new chart, but it looks like it silently errored out

[link to build](https://app.circleci.com/pipelines/github/aws/eks-charts/752/workflows/643fc1bd-9bc4-4e80-a4d4-b038f8684b76/jobs/1894)

error message:
`/home/circleci/project/scripts/publish-charts.sh
/home/circleci/project/scripts/publish-charts.sh: line 11: CIRCLE_TAG: unbound variable
Not a valid semver release tag! Skip charts publish`

**Comment by jeenx** [comment]
@jamestupper It looks like the publish step has been broken for the last few builds. Although, they did cut out a [new release](v0.0.34) and `1.0.6` is available now
```
› helm search repo -l eks/aws-load-balancer-controller
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
eks/aws-load-balancer-controller	1.0.6        	v2.0.0     	AWS Load Balancer Controller Helm chart for Kub...
```

**Comment by jamestupper** [comment]
> @jamestupper It looks like the publish step has been broken for the last few builds. Although, they did cut out a [new release](https://github.com/aws/eks-charts/releases) and `1.0.6` is available now
> 
> ```
> › helm search repo -l eks/aws-load-balancer-controller
> NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
> eks/aws-load-balancer-controller	1.0.6        	v2.0.0     	AWS Load Balancer Controller Helm chart for Kub...
> ```

fantastic. thanks, @jeenx !!

**Comment by kishorj** [comment]
> @kishorj i'm not sure if this is the actual build that publishes the new chart, but it looks like it silently errored out
> 
> [link to build](https://app.circleci.com/pipelines/github/aws/eks-charts/752/workflows/643fc1bd-9bc4-4e80-a4d4-b038f8684b76/jobs/1894)
> 
> error message:
> `/home/circleci/project/scripts/publish-charts.sh /home/circleci/project/scripts/publish-charts.sh: line 11: CIRCLE_TAG: unbound variable Not a valid semver release tag! Skip charts publish`

Charts will get published only when there is a release tag. This is a manual step.

**Pull request merged**
