### PR TITLE
CustomResourceDefinition is not beta anymore since 1.16

### PR DESCRIPTION
**Pull request by Kent1**
Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mogren** [comment]
@Kent1 that's true, but EKS is still supporting 1.14 and 1.15 clusters, so we can't quite remove this yet.

**Comment by Kent1** [comment]
I just saw that aws-vpc-cni 1.6.3 was indeed supported for EKS 1.14, i thought every EKS version had a different aws-vpc-cni version, sorry.
How do you handle versioning here ? I see there no branch or tag ?

**Comment by mogren** [comment]
@Kent1 Currently we do our best to remain backwards compatible when possible, since this CNI is used on AWS outside of EKS as well. For example, we have both [beta and non-beta selectors in the sample configs](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.7/aws-k8s-cni.yaml#L89-L117), since a [1.15 kube-apiserver will still accept 1.13 kubelet](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubelet), and `kubernetes.io/os` and `kubernetes.io/arch` only became GA in 1.14.

**Comment by Kent1** [comment]
Ok thanks for the precisions, i close this PR.

**Pull request closed without merging**
